name: pickrepprot
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - blast=2.9.0
  - hmmer=3.3.0
  - r-base=3.6.1
  - r-optparse=1.6.4
  - r-seqinr=3.6_1
  - r-stringr=1.4.0
  - transdecoder=5.5.0
